export const LOGIN_NURSE_REQUEST = "LOGIN_NURSE_REQUEST";
export const LOGIN_NURSE_ERROR = "LOGIN_NURSE_ERROR";
export const LOGIN_NURSE_SUCCESS = "LOGIN_NURSE_SUCCESS";

export const LOGIN_DOCTOR_SUCCESS = "LOGIN_DOCTOR_SUCCESS";
export const LOGIN_DOCTOR_ERROR = "LOGIN_DOCTOR_ERROR";
export const LOGIN_DOCTOR_REQUEST = "LOGIN_DOCTOR_REQUEST";

export const LOGIN_ADMIN_ERROR = "LOGIN_ADMIN_ERROR";
export const LOGIN_ADMIN_SUCCESS = "LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_REQUEST = "LOGIN_ADMIN_REQUEST";

export const LOGIN_TEACHER_ERROR = "LOGIN_TEACHER_ERROR";
export const LOGIN_TEACHER_SUCCESS = "LOGIN_TEACHER_SUCCESS";
export const LOGIN_TEACHER_REQUEST = "LOGIN_TEACHER_REQUEST";

export const LOGIN_STUDENT_ERROR = "LOGIN_STUDENT_ERROR";
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS";
export const LOGIN_STUDENT_REQUEST = "LOGIN_STUDENT_REQUEST";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const REGISTER_DOCTOR_SUCCESS = " REGISTER_DOCTOR_SUCCESS";
export const REGISTER_DOCTOR_ERROR = "REGISTER_DOCTOR_ERROR";
export const REGISTER_DOCTOR_REQUEST = "REGISTER_DOCTOR_REQUEST";

export const REGISTER_NURSE_SUCCESS = " REGISTER_NURSE_SUCCESS";
export const REGISTER_NURSE_ERROR = "REGISTER_NURSE_ERROR";
export const REGISTER_NURSE_REQUEST = "REGISTER_NURSE_REQUEST";

export const REGISTER_ADMIN_SUCCESS = " REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_ERROR = "REGISTER_ADMIN_ERROR";
export const REGISTER_ADMIN_REQUEST = "REGISTER_ADMIN_REQUEST";

export const REGISTER_TEACHER_SUCCESS = " REGISTER_TEACHER_SUCCESS";
export const REGISTER_TEACHER_ERROR = "REGISTER_TEACHER_ERROR";
export const REGISTER_TEACHER_REQUEST = "REGISTER_TEACHER_REQUEST";

export const REGISTER_STUDENT_SUCCESS = " REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_ERROR = "REGISTER_STUDENT_ERROR";
export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";

export const REGISTER_AMBULANCE_SUCCESS = " REGISTER_AMBULANCE_SUCCESS";
export const REGISTER_AMBULANCE_ERROR = "REGISTER_AMBULANCE_ERROR";
export const REGISTER_AMBULANCE_REQUEST = "REGISTER_AMBULANCE_REQUEST";

export const EDIT_NURSE_SUCCESS = " EDIT_NURSE_SUCCESS";
export const EDIT_NURSE_ERROR = "EDIT_NURSE_ERROR";
export const EDIT_NURSE_REQUEST = "EDIT_NURSE_REQUEST";

export const EDIT_DOCTOR_SUCCESS = " EDIT_DOCTOR_SUCCESS";
export const EDIT_DOCTOR_ERROR = "EDIT_DOCTOR_ERROR";
export const EDIT_DOCTOR_REQUEST = "EDIT_DOCTOR_REQUEST";

export const EDIT_TEACHER_SUCCESS = " EDIT_TEACHER_SUCCESS";
export const EDIT_TEACHER_ERROR = "EDIT_TEACHER_ERROR";
export const EDIT_TEACHER_REQUEST = "EDIT_TEACHER_REQUEST";

export const EDIT_ADMIN_SUCCESS = " EDIT_ADMIN_SUCCESS";
export const EDIT_ADMIN_ERROR = "EDIT_ADMIN_ERROR";
export const EDIT_ADMIN_REQUEST = "EDIT_ADMIN_REQUEST";

export const EDIT_STUDENT_SUCCESS = " EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR";
export const EDIT_STUDENT_REQUEST = "EDIT_STUDENT_REQUEST";

export const SEND_PASSWORD_SUCCESS = " SEND_PASSWORD_SUCCESS";
export const SEND_PASSWORD_ERROR = "SEND_PASSWORD_ERROR";
export const SEND_PASSWORD_REQUEST = "SEND_PASSWORD_REQUEST";

export const FORGET_PASSWORD_SUCCESS = " FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
